function [result] = cspice_gfrfov( inst,   raydir, rframe, abcorr, ...
                                  obsrvr, step,   cnfine, nintvls)
  switch nargin
     case 8
        inst    = zzmice_str(inst);
        raydir  = zzmice_dp(raydir);
        rframe  = zzmice_str(rframe);
        abcorr  = zzmice_str(abcorr);
        obsrvr  = zzmice_str(obsrvr);
        step    = zzmice_dp(step);
        cnfine  = zzmice_win(cnfine);
        nintvls = zzmice_int(nintvls,    [1, int32(inf)/2] );
     otherwise
        error ( [ 'Usage: [result] = cspice_gfrfov( `inst`, ' ...
                               'raydir[3], `rframe` '         ...
                               '`abcorr`, `obsrvr`, step, cnfine, nintvls)' ] )
  end
  try
     [result] = mice('gfrfov_c',  inst,   ...
                                  raydir, ...
                                  rframe, ...
                                  abcorr, ...
                                  obsrvr, ...
                                  step,   ...
                                  [zeros(6,1); cnfine], nintvls);
  catch spiceerr
     rethrow(spiceerr)
  end