function [spoint, dist, pltid] = cspice_subsol_pl02( handle, dladsc,       ...
                                                     method,  target,      ...
                                                     et,     abcorr,       ...
                                                     obsrvr         )
   switch nargin
      case 7
         handle = zzmice_int( handle );
         dladsc = zzmice_int( dladsc );
         method = zzmice_str( method );
         target = zzmice_str( target );
         et     = zzmice_dp( et );
         abcorr = zzmice_str( abcorr );
         obsrvr = zzmice_str( obsrvr );
      otherwise
         error ( [ 'Usage: [spoint(3), dist, pltid] = '                    ...
                            'cspice_subsol_pl02( handle, '                 ...
                            'dladsc(SPICE_DLA_DSCSIZ), `method`, '         ...
                            '`target`, et, `abcorr`, `obsrvr` )' ] )
   end
   try
      [spoint, dist, pltid] = mice( 'subsol_pl02',                         ...
                                    handle, dladsc, method,                ...
                                    target, et,     abcorr, obsrvr );
   catch spiceerr
      rethrow(spiceerr)
   end