function cspice_ckw03( handle, ...
                       begtim, ...
                       endtim, ...
                       inst,   ...
                       ref,    ...
                       avflag, ...
                       segid,  ...
                       sclkdp, ...
                       quats,  ...
                       avvs,   ...
                       starts )
   switch nargin
      case 11
         handle = zzmice_int(handle);
         begtim = zzmice_dp(begtim);
         endtim = zzmice_dp(endtim);
         avflag = zzmice_int(avflag);
         inst   = zzmice_int(inst);
         sclkdp = zzmice_dp(sclkdp);
         quats  = zzmice_dp(quats);
         avvs   = zzmice_dp(avvs);
         starts = zzmice_dp(starts);
      otherwise
         error ( [ 'Usage: '                    ...
                   'cspice_ckw03( handle, '     ...
                                 'begtim, '     ...
                                 'endtim, '     ...
                                 'inst, '       ...
                                 'ref, '        ...
                                 'avflag, '     ...
                                 'segid, '      ...
                                 'sclkdp(N), '  ...
                                 'quats(4,N), ' ...
                                 'avvs(3,N), '  ...
                                 'starts(M))' ] )
   end
   try
      mice( 'ckw03_c', handle, begtim, endtim, inst, ref,  avflag,  ...
                       segid,  sclkdp,  quats, avvs, starts )
   catch spiceerr
      rethrow(spiceerr)
   end