function [ xptarr, fndarr] = cspice_dskxv(  pri,             ...
                                            target, nsurf,   ...
                                            srflst, et,      ...
                                            fixref, vtxarr,  ...
                                            dirarr )
   switch nargin
      case 8
         pri     = zzmice_int(pri);
         target  = zzmice_str(target);
         nsurf   = zzmice_int(nsurf);
         srflst  = zzmice_int(srflst);
         et      = zzmice_dp(et);
         fixref  = zzmice_str(fixref);
         vtxarr  = zzmice_dp(vtxarr);
         dirarr  = zzmice_dp(dirarr);
      otherwise
         error ( [ 'Usage: [ xptarr(3,n), fndarr(n)] = '   ...
                   'cspice_dskxv( pri, '                   ...
                   '`target`, nsurf, srflst(nsurf), et, '  ...
                   '`fixref`, vtxarr(3,n), dirarr(3,n) )' ] )
   end
   try
      [ xptarr, fndarr] = mice( 'dskxv_c', pri,    target, ...
                                           nsurf,  srflst, ...
                                           et,     fixref, ...
                                           vtxarr, dirarr );
      fndarr = zzmice_logical(fndarr);
   catch spiceerr
      rethrow(spiceerr)
   end