function cspice_ckw02( handle, ...
                       begtim, ...
                       endtim, ...
                       inst,   ...
                       ref,    ...
                       segid,  ...
                       start,  ...
                       stop,   ...
                       quats,  ...
                       avvs,   ...
                       rates )
   switch nargin
      case 11
         handle = zzmice_int(handle);
         begtim = zzmice_dp(begtim);
         endtim = zzmice_dp(endtim);
         inst   = zzmice_int(inst);
         ref    = zzmice_str(ref);
         segid  = zzmice_str(segid);
         start  = zzmice_dp(start);
         stop   = zzmice_dp(stop);
         quats  = zzmice_dp(quats);
         avvs   = zzmice_dp(avvs);
         rates  = zzmice_dp(rates);
      otherwise
         error ( [ 'Usage: '                    ...
                   'cspice_ckw02( handle, '     ...
                                 'begtim, '     ...
                                 'endtim, '     ...
                                 'inst, '       ...
                                 'ref, '        ...
                                 'segid, '      ...
                                 'start(N), '   ...
                                 'stop(N), '    ...
                                 'quats(4,N), ' ...
                                 'avvs(3,N)) '  ...
                                 'rates(N)' ] )
   end
   try
      mice( 'ckw02_c', handle, ...
                       begtim, ...
                       endtim, ...
                       inst,   ...
                       ref,    ...
                       segid,  ...
                       start,  ...
                       stop,   ...
                       quats,  ...
                       avvs,   ...
                       rates )
   catch spiceerr
      rethrow(spiceerr)
   end