function [ nv, np, nvxtot, vtxbds, voxsiz, voxori,    ...
           vgrext, cgscal, vtxnpl, voxnpt, voxnpl ] = ...
           cspice_dskb02( handle, dladsc )
   switch nargin
      case 2
         handle = zzmice_int( handle );
         dladsc = zzmice_int( dladsc );
      otherwise
         error ( [ 'Usage: [nv, np, '           ...
                   'nvxtot, vtxbds(2,3), '      ...
                   'voxsiz, voxori(3,1), '      ...
                   'vgrext(3,1), cgscal, '      ...
                   'vtxnpl, voxnpt, voxnpl] = ' ...
                   'cspice_dskb02( handle, dladsc )' ] )
   end
   try
      [ nv, np, nvxtot, vtxbds, voxsiz, voxori,    ...
      vgrext, cgscal, vtxnpl, voxnpt, voxnpl ] = ...
      mice( 'dskb02_c', handle, dladsc  );
   catch spiceerr
      rethrow(spiceerr)
   end