function [trgepc, obspos, trmpts, pltids] =                                ...
                                         cspice_term_pl02( handle, dladsc, ...
                                                   trmtyp, source, target, ...
                                                   et,     fixref, abcorr, ...
                                                   obsrvr, npts           )
   switch nargin
      case 10
         handle  = zzmice_int( handle );
         dladsc  = zzmice_int( dladsc );
         trmtyp  = zzmice_str( trmtyp );
         source  = zzmice_str( source );
         target  = zzmice_str( target );
         et      = zzmice_dp( et );
         fixref  = zzmice_str( fixref );
         abcorr  = zzmice_str( abcorr );
         obsrvr  = zzmice_str( obsrvr );
         npts    = zzmice_int( npts );
      otherwise
         error ( [ 'Usage: [trgepc, obspos(3), '                           ...
                  'trmpts(3,npts), pltids(npts)] = '                       ...
                  'cspice_term_pl02( handle, dladsc(SPICE_DLA_DSCSIZ), '   ...
                  '`trmtyp`, `source`, `target`, '                         ...
                  'et, `fixref`, `abcorr`, `obsrvr`, npts )' ] )
   end
   try
      [trgepc, obspos, trmpts, pltids] = mice( 'term_pl02',                ...
                                   handle, dladsc, trmtyp, source, target, ...
                                   et,     fixref, abcorr, obsrvr, npts );
   catch spiceerr
      rethrow(spiceerr)
   end