function cspice_dskw02( handle, ...
                        center, ...
                        surfid, ...
                        dclass, ...
                        frame,  ...
                        corsys, ...
                        corpar, ...
                        mncor1, ...
                        mxcor1, ...
                        mncor2, ...
                        mxcor2, ...
                        mncor3, ...
                        mxcor3, ...
                        first,  ...
                        last,   ...
                        vrtces, ...
                        plates, ...
                        spaixd,  ...
                        spaixi )
   switch nargin
      case 19
         handle = zzmice_int(handle);
         center = zzmice_int(center);
         surfid = zzmice_int(surfid);
         dclass = zzmice_int(dclass);
         frame  = zzmice_str(frame);
         corsys = zzmice_int(corsys);
         corpar = zzmice_dp(corpar);
         mncor1 = zzmice_dp(mncor1);
         mxcor1 = zzmice_dp(mxcor1);
         mncor2 = zzmice_dp(mncor2);
         mxcor2 = zzmice_dp(mxcor2);
         mncor3 = zzmice_dp(mncor3);
         mxcor3 = zzmice_dp(mxcor3);
         first  = zzmice_dp(first);
         last   = zzmice_dp(last);
         vrtces = zzmice_dp(vrtces);
         plates = zzmice_int(plates);
         spaixd = zzmice_dp(spaixd);
         spaixi = zzmice_int(spaixi);
      otherwise
         error ( [ 'Usage: cspice_dskw02( handle, center, surfid, dclass, ' ...
                   '`frame`, corsys, corpar(2), mncor1, mxcor1, mncor2, '   ...
                   'mxcor2, mncor3, mxcor3, first, last, vrtces(3,m), '     ...
                   'plates(3,n), spaixd(p), spaixi(q) )' ] )
   end
   try
      mice('dskw02_c', handle, center, surfid, dclass, frame,  ...
                       corsys, corpar, mncor1, mxcor1, mncor2, ...
                       mxcor2, mncor3, mxcor3, first,  last,   ...
                       vrtces, plates, spaixd, spaixi  );
   catch spiceerr
      rethrow(spiceerr)
   end