function [ trgepc, obspos, trmpts] = cspice_edterm( trmtyp, source, ...
                                                    target, et,     ...
                                                    fixref, abcorr, ...
                                                    obsrvr, npts)
   switch nargin
      case 8
         trmtyp = zzmice_str(trmtyp);
         source = zzmice_str(source);
         target = zzmice_str(target);
         et     = zzmice_dp(et);
         fixref = zzmice_str(fixref);
         abcorr = zzmice_str(abcorr);
         obsrvr = zzmice_str(obsrvr);
         npts   = zzmice_int(npts);
      otherwise
         error ( ['Usage: [trgepc, obspos(3), trmpts(3,npts)] = ' ...
                        'cspice_edterm( `trmtyp`, `source`, `target`, ' ...
                                       'et,       `fixref`, `abcorr`, ' ...
                                       '`obsrvr`, npts)' ]  )
   end
   try
      [ trgepc, obspos, trmpts] = mice( 'edterm_c', trmtyp, source, ...
                                                    target, et,     ...
                                                    fixref, abcorr, ...
                                                    obsrvr, npts);
   catch spiceerr
      rethrow(spiceerr)
   end