function [tanpt, alt,    range,                                             ...
          srfpt, trgepc, srfvec] = cspice_tangpt( method, target, et,       ...
                                                  fixref, abcorr, corloc,   ...
                                                  obsrvr, dref,   dvec    )
   switch nargin
      case 9
         method = zzmice_str(method);
         target = zzmice_str(target);
         et     = zzmice_dp(et);
         fixref = zzmice_str(fixref);
         abcorr = zzmice_str(abcorr);
         corloc = zzmice_str(corloc);
         obsrvr = zzmice_str(obsrvr);
         dref   = zzmice_str(dref);
         dvec   = zzmice_dp(dvec);
      otherwise
         error ( [ 'Usage: [tanpt(3), alt, range, srfpt(3), trgepc, '       ...
                   'srfvec(3)] = '                                          ...
                   'cspice_tangpt( `method`, `target`, et, `fixref`, '      ...
                   '`abcorr`, `corloc`, `obsrvr`, `dref`, dvec(3) )' ] )
   end
   try
      [tanpt, alt,    range,                                                ...
       srfpt, trgepc, srfvec] = mice( 'tangpt_c', method,                   ...
                                      target,     et,                       ...
                                      fixref,     abcorr,                   ...
                                      corloc,     obsrvr,                   ...
                                      dref,       dvec    );
   catch spiceerr
      rethrow(spiceerr)
   end