function [xpt, handle, dladsc, dskdsc, dc, ic, found] =          ...
                                 cspice_dskxsi( pri,             ...
                                                target, nsurf,   ...
                                                srflst, et,      ...
                                                fixref, vertex,  ...
                                                raydir )
   switch nargin
      case 8
         pri     = zzmice_int(pri);
         target  = zzmice_str(target);
         nsurf   = zzmice_int(nsurf);
         srflst  = zzmice_int(srflst);
         et      = zzmice_dp(et);
         fixref  = zzmice_str(fixref);
         vertex  = zzmice_dp(vertex);
         raydir  = zzmice_dp(raydir);
      otherwise
         error ( [ 'Usage: [ xpt(3), handle, '              ...
                   'dladsc(SPICE_DLA_DSCSIZ), '             ...
                   'dskdsc(SPICE_DSK_DSCSIZ), '             ...
                   'dc(SPICE_DSKXSI_DCSIZE), '              ...
                   'ic(SPICE_DSKXSI_ICSIZE), found] = '     ...
                   'cspice_dskxsi( pri, `target`, nsurf, '  ...
                   'srflst(nsurf), et, `fixref`, '          ...
                   'vertex(3), raydir(3) )' ] )
   end
   try
      [xpt, handle, dladsc, dskdsc, dc, ic, found] = mice( 'dskxsi_c', ...
                                                       pri,    target, ...
                                                       nsurf,  srflst, ...
                                                       et,     fixref, ...
                                                       vertex, raydir );
      found = zzmice_logical(found);
   catch spiceerr
      rethrow(spiceerr)
   end