function cspice_spkw08( handle, ...
                        body,   ...
                        center, ...
                        frame,  ...
                        first,  ...
                        last,   ...
                        segid,  ...
                        degree, ...
                        states, ...
                        begtim, ...
                        step )
   switch nargin
      case 11
         handle  = zzmice_int(handle);
         body    = zzmice_int(body);
         center  = zzmice_int( center);
         frame   = zzmice_str(frame);
         first   = zzmice_dp(first);
         last    = zzmice_dp(last);
         segid   = zzmice_str(segid);
         degree  = zzmice_int(degree);
         states  = zzmice_dp(states);
         begtim  = zzmice_dp(begtim);
         step    = zzmice_dp(step);
      otherwise
         error ( [ 'Usage: '                ...
                   'cspice_spkw08( handle, '...
                                  'body, '  ...
                                  'center, '...
                                  'frame, ' ...
                                  'first, ' ...
                                  'last, '  ...
                                  'segid, ' ...
                                  'degree, '...
                                  'states, '...
                                  'begtim, '...
                                  'step )' ] )
   end
   try
      mice( 'spkw08_c', handle, ...
                        body,   ...
                        center, ...
                        frame,  ...
                        first,  ...
                        last,   ...
                        segid,  ...
                        degree, ...
                        states, ...
                        begtim, ...
                        step )
   catch spiceerr
      rethrow(spiceerr)
   end