function cspice_ckw01( handle, ...
                       begtim, ...
                       endtim, ...
                       inst  , ...
                       ref   , ...
                       avflag, ...
                       segid , ...
                       sclkdp, ...
                       quats , ...
                       avvs )
   switch nargin
      case 10
         handle = zzmice_int(handle);
         begtim = zzmice_dp(begtim);
         endtim = zzmice_dp(endtim);
         avflag = zzmice_int(avflag);
         inst   = zzmice_int(inst);
         sclkdp = zzmice_dp(sclkdp);
         quats  = zzmice_dp(quats);
         avvs   = zzmice_dp(avvs);
      otherwise
         error ( [ 'Usage: '                    ...
                   'cspice_ckw01( handle, '     ...
                                 'begtim, '     ...
                                 'endtim, '     ...
                                 'inst, '       ...
                                 'ref, '        ...
                                 'avflag, '     ...
                                 'segid, '      ...
                                 'sclkdp(N), '  ...
                                 'quats(4,N), ' ...
                                 'avvs(3,N))' ] )
   end
   try
      mice( 'ckw01_c', handle, begtim,  endtim,  inst,   ref,  ...
                       avflag, segid,   sclkdp,  quats,  avvs )
   catch spiceerr
      rethrow(spiceerr)
   end