function [npts, points, epochs, trmvcs] = cspice_termpt( method, ilusrc,  ...
                                            target, et,   fixref, abcorr, ...
                                            corloc, obsrvr, refvec,       ...
                                            rolstp, ncuts,  schstp,       ...
                                            soltol, maxn )
   switch nargin
      case 14
         method = zzmice_str(method);
         ilusrc = zzmice_str(ilusrc);
         target = zzmice_str(target);
         et     = zzmice_dp(et);
         fixref = zzmice_str(fixref);
         abcorr = zzmice_str(abcorr);
         corloc = zzmice_str(corloc);
         obsrvr = zzmice_str(obsrvr);
         refvec = zzmice_dp(refvec);
         rolstp = zzmice_dp(rolstp);
         ncuts  = zzmice_int(ncuts);
         schstp = zzmice_dp(schstp);
         soltol = zzmice_dp(soltol);
         maxn   = zzmice_int(maxn);
      otherwise
         error ( ['Usage: [npts, points, epochs, trmvcs] = '      ...
                  'cspice_termpt( `method`, `ilusrc`, `target`, ' ...
                                 'et, `fixref`, `abcorr`, '       ...
                                 '`corloc`, `obsrvr`, refvec, '   ...
                                 'rolstp, ncuts, schstp, '        ...
                                 'soltol, maxn )' ]  )
   end
   try
      [npts, points, epochs, trmvcs] = mice( 'termpt_c',                  ...
                                                  method, ilusrc, target, ...
                                                  et,     fixref, abcorr, ...
                                                  corloc, obsrvr, refvec, ...
                                                  rolstp, ncuts,  schstp, ...
                                                  soltol, maxn );
   catch spiceerr
      rethrow(spiceerr)
   end