function [y] = zzmice_win(x)
   if( ~isequal(nargin,1) )
      error( 'MICE(USAGE): y = zzmice_win( x)' )
   end
   if( isequal( x, [] ) )
      y = zeros(0,1);
      return;
   end
   x_dim     = size(x);
   [ N, col] = size(x);
   if( isnumeric(x)        && ...
       zzmice_even(N)      && ...
       (col == 1)          && ...
       issorted(x)         && ...
       isequal(size(x_dim), [1,2])   )
      y = double(x);
   else
      error( ['MICE(BADARG): Improper type of input '          ...
              'argument passed to function. Input expected ' ...
              'as numeric Nx1 array in ascending order, with ' ...
              'either an even number of elements or an empty ' ...
              '0x1 array.' ] )
   end
function bool = zzmice_even(n)
   bool = ( mod(n,2)==0 );